homework№1
alexxten/homework_23 pull request #1
Opened 2017-10-13 16:24 UTC by alexxten

2017-10-13 16:55 UTC, mlshv requested changes
формат, картинки, списки

2017-10-13 16:55 UTC, mlshv commented on homework№1/ДЗ №1.html
> +  </head>
отформатируй код

2017-10-13 16:55 UTC, mlshv commented on homework№1/ДЗ №1.html
> +<figure> <p><img src="C:\Users\Master\Desktop\IT-centre\images\Основатели_Fairchild_в_1988_-_NYTimes.jpg" alt="Воссоединение «восьмёрки» в 1988 году.Стоят, слева направо: Гринич, Ласт, Эрни, Бланк, К
ссылка на картинку

2017-10-13 16:55 UTC, mlshv commented on homework№1/ДЗ №1.html
> + <p>•	Джексон, Тим. Intel: взгляд изнутри = Inside Intel: Andy Grove and the Rise of the World's Most Powerful Chip Company. — Лори, 1999. — 346 p. — <a href="https://ru.wikipedia.org/wiki/%D0%A1%D0%
ul юзай

2017-10-16 12:59 UTC, mlshv commented
![image](https://user-images.githubusercontent.com/16861579/31613158-ea7e3cac-b28a-11e7-882f-76a868a1c499.png)
чем отличаются эти директории? куда мне смотреть?

2017-10-16 13:18 UTC, alexxten commented
в ту, которая без №

2017-10-16 14:00 UTC, closed without merging