Add files via upload
alexxten/homework_23 pull request #4
Opened 2017-10-25 10:50 UTC by alexxten

2017-10-26 14:57 UTC, mlshv requested changes

2017-10-26 14:57 UTC, mlshv commented on homework3/style.css
> +font-style:italic;
это что ещё за формат такой? чужие ПРы совсем не смотришь, да?

2017-10-26 14:57 UTC, mlshv commented on homework3/style.css
> +border-color:#dddddd;
`#ddd;`

2017-10-26 14:57 UTC, mlshv commented on homework3/style.css
> +    color:#222222;
`#222;`

2017-10-26 14:57 UTC, mlshv commented on homework3/style.css
> +    border-bottom-color: #aaaaaa
`#aaa;`

2017-10-26 14:57 UTC, mlshv commented on homework3/style.css
> +    border-bottom-color: #aaaaaa;
`#aaa;`

2017-10-26 14:57 UTC, mlshv commented on homework3/style.css
> +    border-color:#dddddd;
`#ddd;`

2017-10-26 14:57 UTC, mlshv commented on homework3/style.css
> +    background-color:#eeeeee;
`#eee;`

2017-10-26 14:57 UTC, mlshv commented on homework3/style.css
> +    margin-right:40px;
`margin: 15px 40px;`

2017-10-26 14:57 UTC, mlshv commented on homework3/style.css
> +    font-size:0,8rem;
это невалидный код

гугли синтаксис чисел с плавающей точкой в css

2017-10-26 14:57 UTC, mlshv commented on homework3/style.css
> +background-color: #eeeeee;
`#eee;`

2017-10-26 14:57 UTC, mlshv commented on homework3/style.css
> +    color:#888888;
`#888`;

2017-10-26 14:58 UTC, mlshv commented
и переименуй ПР

2017-10-30 16:59 UTC, mlshv requested changes

2017-10-30 16:59 UTC, mlshv commented on homework3/style.css
> +    font-family: "Roboto", sans-serif;
2 пробела отступ

2017-10-30 16:59 UTC, mlshv commented on homework3/style.css
> +padding: 15px;
бам

2017-11-04 08:42 UTC, mlshv commented
слушай, я же говорю, отсутп 2 пробела

2017-11-05 17:58 UTC, alexxten commented
2 отступа- это принципиально? я хз почему, но 4 получилось, когда я табом делала в visual code

2017-11-09 10:47 UTC, merged